travis:
  secure:
    BINSTAR_TOKEN: gQ95ZnPB5CgVVUYrkrGWqZ188pyHRA3QTqVmxqjiuCCKh20BftpcwuFIYjRUlpTI6fTo52n4Gd92Czyw1LoM96Eg2sdDF974re2Zp3HdxjjvlZXHjTTiUZfPWejYSINeVda+wMIywaIUxSCuFI9rbq3yZ3f+O7XIK9o6A1aLTuqFk4mIAfiVJOygzpBYZv0IQrgfE9dqjooedJDd8LILtNyGDpowtdrIgNHpJrs6KpWkV7kPC1KM8YPHCLvRgf9MXRkzVvR+3quanSs+2UijzGvx0JifNCJPJWpFPlr2KlbG0yeaomzjGINQV0srfMmQoKwt1D5RyY1isNNp+4h5CU0TL9C5HAI6FBcGCH1m6XCMzN44h0bsWQBEsOZLR2u7FbnQ4Vjxxy+zAob0nVX4i/LmHSlWMMyGVkeTcLFTlXHIRMup/x4mNtcz0sqfiCLdJ4Md/bp3IoTzivQEJXqEJxI6Q6cRB2xAMtR8UAGVWJtCMD2OWpgKGdb5+Gaq1ItbIWFNDM+cWA1RNSpXi8iEooZEvXNYzqGNrI4VCFO99UmhWefOujBI7f79H2/ta742vGOZAWboKYwTcnfvj+g7ZK+lbjgzGcnO/CbNO3BGgj/bBvGzn5SIOfrTjNNWfXivqM0Hjh9dWi4tfBFQ9Cle09eoMIynZxUzPxn+n+Dct1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
