travis:
  secure:
    BINSTAR_TOKEN: nOED5CJwHR6i0V2fQazLa7CVZXqLWN47E0749y7JqySVffsb9BLBJg/4QdGBXsIqpA3Bfnzhb3piH4kLo/cEtxg2sra3dRbiOoSLx/EJhxjgtHv8o3z0g6lB5K4aRy6Pi3UE4LFjZl86y1s1W54qRLSQ4KgZa4zeeXjhEMHfObbJXdT2zV0ow34bJa34aT5Aw9VsZDQUFSk3idiqdYeq/mmrbnPRmZHO6sTO6hcG2hCgqF1mgZLRZoqOSFXASIDp6ANwMHTN16P1mwmNmg0MAjlYmozCZl+2Gq7Pda9JlO379qtgEg+xf1BYHNZBurKOYO/YO8L+lIxsAVuYxYZU028h+hI+e87kcP0V2PvNY7aVxYVouyqjskmrtc51rJPxzal0ERtLvMnYHAMPv6vmotVryk1N1erItThPYzyywppVgfjmIXPfe1NMO2z+n6ZArA/oiaYciwt0hFuFY1BWxF5xSsl1eG2xHyYL0DIMYS9tVNm+qUh4lNp9ocrOT/AGN60w64T54JH2iBI/CbAgUOSYYOxP9aOER9AG/rEi5E9pn3lo/BDfnxamSEVNzZE01aIpsIMrKOClB7S+KTdVgdJMYu38JlL5TqK89Mxuex/g///bd0Mz79Y14IPskWBt+0EOaewdt9vWbRzQ8TAzlb36S3s0H2Nuhv+p5pPU5qg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
